### ISSUE TITLE
Change DefaultCommandPrefix from Appclusive to Apc

### ISSUE THREAD

**Issue by dfch** [dfensgmbh/biz.dfch.PS.Appclusive.Client#10]
Currently the `DefaultCommandPrefix` is set to `Appclusive` resulting in relatively long Cmdlet names. I suggest to change this infix to `Apc`.

| Current                              	| Suggestion with Apc           	|
|--------------------------------------	|-------------------------------	|
| `Get-AppclusiveManagementCredential` 	| `Get-ApcManagementCredential` 	|
| `Get-AppclusiveNode`                 	| `Get-ApcNode`                 	|

This will probably affect the following

* wiki help
* integration tests
* dependent modules such `net.srse.swi.dass.scripts`

**Comment by dfch** [comment]
@rufer7 did you know any dependencies I missed in the list?

**Comment by rufer7** [comment]
Should be all that will be affected
