### ISSUE TITLE
Nodes - It is possible to make a node parent/child itself

### ISSUE THREAD

**Issue by gaestu** [dfensgmbh/biz.dfch.PS.Appclusive.Client#13]
It is possible to make a node child or parent of its own.

If a node is his own child/parent the LoadProperty children load his own and you have the same effect with LoadProperty parent.

**Update**
```
$node.ParentId = $node.Id;
$svc.Core.UpdateObject($node);
$svc.Core.SaveChanges();
```
**Result**
```
Type          : biz.dfch.CS.Appclusive.Api.Core.Node
Parameters    : {}
ParentId      : 790
Id            : 790
Tid           : 11111111-1111-1111-1111-111111111111
Name          : TestNode Child
Description   : TestNode used in test
CreatedBy     : WIN-8A036G6JVPJ\Administrator
ModifiedBy    : WIN-8A036G6JVPJ\Administrator
Created       : 17.11.2015 16:01:51 +01:00
Modified      : 17.11.2015 16:01:51 +01:00
RowVersion    : {0, 0, 0, 0...}
Parent        : biz.dfch.CS.Appclusive.Api.Core.Node
Children      : {TestNode Child}
IncomingLinks : {}
OutgoingLinks : {}
```

**Comment by rufer7** [comment]
duplicates dfch/biz.dfch.CS.Appclusive#118

**Comment by pbimpisidis** [comment]
this is still an issue, when using the following:
$svc.Core.SetLink($node, "Parent", $node);
$updateResult = $Svc.Core.SaveChanges();

it doesn't throw error, the parent Id of the node becomes the same as its Id and the node cannot be deleted (unless another node becomes its parentId)
