### ISSUE TITLE
Implement Tid for Get Cmdlets

### ISSUE THREAD

**Issue by dfch** [dfensgmbh/biz.dfch.PS.Appclusive.Client#17]
Every *Get*-Cmdlet should support a parameter to filter for specific tenant ids

Example: `Get-ManagementCredential -tid 28f89797-144a-466a-a9fd-8e06e0f2af9e`

**Comment by rufer7** [comment]
@dfch this would not be necessary anymore as we have a tenant filter directly on the API right? If you agree please close this issue

**Comment by dfch** [comment]
this is actually not needed, as the client will pass a `Tid` header to the application. and if a `UberAdmin` calls the application tenant filtering will be disabled
