### ISSUE TITLE
Fix Pester Tests for Cmdlets

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.PS.Appclusive.Client#19]
* [x] Fix pester tests for Cmdlets (Tests in `src` directory)
  * Failing tests/contexts
    * [x] Format-Exception.Tests.ps1
    * [x] Get-EntityKindID-Resolver (1 Fail)
    * [x] Get-Interface.Tests.ps1 (Will be fixed by #40)
    * [x] Get-Job (2 Fails)
    * [x] Get-ManagementUri (1 Fail)
    * [x] Get-Node (3 Fails)
    * [x] Get-SessionTenant.Tests (2 Fails)
    * [x] TenantInformation (1 Fail) in Get-Tenant.Tests.ps1
    * [x] TenantInformation (1 Fail) in Get-User.Tests.ps1
    * [x] Get-Version (5 Fails)
    * [x] Invoke-EntityAction (2 Fails)
    * [x] New-Node (2 Fails)
    * [x] Pop-ChangeTracker (3 Fails)
    * [x] Push-ChangeTracker (1 Fail)
    * [x] Remove-Node (3 Fails)
    * [x] Set-Node (3 Fails)
    * [x] Set-SessionTenant (3 Fails)
    * [x] Test-Status (1 Fail)
    * [x] Remove-Connector (1 Fail)
    * [x] Remove-Interface (2 Fails)
  * [x] Check, that tests clean test data

Verify that every test cleans up it's test data

**Comment by rufer7** [comment]
relates to #7

**Comment by stevenpi** [comment]
@rufer7 there are still tests for `Connectors` and `Interfaces` that do not clean up test data...
