### ISSUE TITLE
Add missing Cmdlets

### ISSUE THREAD

**Issue by dfch** [dfensgmbh/biz.dfch.PS.Appclusive.Client#2]
# TODO

## General

- [x] Enter-Server
- [x] Import-Module.ps1
- [x] Format-ResultAs
- [x] Pop-ChangeTracker
- [x] Push-ChangeTracker
- [x] Remove-Entity
- [x] Invoke-EntityAction

# Core.svc

- [ ] Aces
- [ ] Acls
- [ ] ActiveDirectoryUsers
- [ ] Approvals
- [ ] CartItems
- [ ] Carts
- [ ] CatalogueItems
- [ ] Catalogues
- [x] EntityKinds
- [x] ExternalNodes
- [ ] Gates
- [x] Jobs
- [x] KeyNameValues
- [ ] Assoc
- [x] ManagementCredentials
- [x] ManagementUris
- [x] Nodes
- [ ] OrderItems
- [ ] Orders
- [x] Users

## Diagnostics.svc

- [ ] Endpoints
- [x] Endpoints/Ping
- [x] Endpoints/Echo
- [x] Endpoints/Time

**Comment by rufer7** [comment]
@dfch what's the state here? Did @schefDev do something here right? If yes, please assign the issue to him so that he can update it

**Comment by dfch** [comment]
@schefDev can you pls update the issue with the stuff you implemented? thx

**Comment by rufer7** [comment]
@dfch I suggest closing this issue and open issues for specific cmdlets as soon as they are needed. What do you think?

**Comment by rufer7** [comment]
We will close this issue and create new issues for specific cmdlets as soon as they are needed.
