### ISSUE TITLE
Enable setting Tenant Header

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.PS.Appclusive.Client#20]
The Appclsuive.Client project has to have an additional property or Cmdlet for setting the tenant (@dfch suggested to implement this via Enter-Server, as we then do not have caching problems of the entity tracker, which might return entities which are in the cache but not returned under the current tenant ).

relates to dfensgmbh/biz.dfch.CS.Appclusive.Api#9

**Comment by dfch** [comment]
@rufer7 isn't this already implemented by the `Set-SessionTenant` Cmdlet? or what do you actually want to achieve here?

**Comment by dfch** [comment]
according to @rufer7 the `Set-SessionTenant` implements this functionality. However, it is not clear whether this has been *fully* implemented.

TODO

* Check if the current implementation of `Set-SessionTenant` implements and sets the tenant header for all endpoints
* Create and update tests accordingly

**Comment by dfch** [comment]
* implemented by e1b56ba0c301eaeccdef9bf2201398c33d70f3e8
* FAB is not yet included in Api, see dfensgmbh/biz.dfch.CS.Appclusive.Api#15
