### ISSUE TITLE
Remove-Node fails with FOREIGN_KEY_CONSTRAINT_VIOLATION

### ISSUE THREAD

**Issue by dfch** [dfensgmbh/biz.dfch.PS.Appclusive.Client#23]
Using `Remove-Node` might fail due to the following circumstances:

* [x] it has subordinate child `Node` entities

  this is supposed to fail, as we do not support recursive delete
* [x] it has referencing `EntityBag` entities
* [x] it has a referencing `ExternalNode` entity
* [x] it has a referencing `Acl` and `Ace`s entities

Furthermore, the following items are *NOT* properly deleted when `Remove-Node` is executed:

* a referencing `Job` entity

See [Remove-NodeWithAttachedEntities.ps1](https://github.com/dfensgmbh/biz.dfch.PS.Appclusive.Scriplets/blob/develop/src/Remove-NodeWithAttachedEntities.ps1) for code that performs the necessary steps in order.

**Comment by dfch** [comment]
As of [`2.17.0`](https://github.com/dfch/biz.dfch.CS.Appclusive/releases/tag/2.17.0) Appclusive now handles the deletion of nodes and related entities on its own. Note: this is *NO* recuursive delete.

Check again if the `Remove-Node` Cmdlet needs further adjustments, eg. `-Recurse` switch.

see dfch/biz.dfch.CS.Appclusive#269

**Comment by dfch** [comment]
@pbimpisidis pls check if this is fixed now, as it should have been implemented in the Controller already

**Comment by pbimpisidis** [comment]
it's fixed. When a parent node is deleted the acl, aces, externalnode & entitybag are removed. When it has a child node then deletion fails.
