### ISSUE TITLE
Interfaces and Connectors Cmdlet

### ISSUE THREAD

**Issue by dfch** [dfensgmbh/biz.dfch.PS.Appclusive.Client#27]
* [x] CREATE Interface
* [x] READ Interface
* [x] UPDATE Interface
* [x] DELETE Interface

* [x] CREATE Connector
* [x] READ Connector
* [x] UPDATE Connector
* [x] DELETE Connector
* [x] `Remove-Connector -Test`

* [x] `Get-Interfaces -Id 42 -Providers`
* [x] `Get-Interfaces -Id 42 -Consumers`

* [x] `Get-EntityKind -Id 42 -Connectors`
* [x] `Get-EntityKind -Id 42 -Interfaces`

* [x] `Get-EntityKind -ProvidesInterfaces 1337`
* [x] `Get-EntityKind -RequiresInterfaces 1337`

* [x] `Get-Node -ProvidesInterfaces 1337`
* [x] `Get-Node -RequiresInterfaces 1337`

* [x] `Test-Connectors -Provider EkId1 -Consumer EkId2`
* [x] `Test-Connectors -NodeId 1 -Consumer EkId2`

``` powershell
$continuation = $true;
$response = $svc.Core.EntityKinds.Execute();
do
{
	foreach($ek in $response) 
	{ 
		if([biz.dfch.CS.Appclusive.Public.Constants+EntityKindId]::IntrinsicEnd.value__ -ge $ek.Id)
		{
			continue;
		}
		if($ek.Name -eq $ek.Version)
		{
			Log-Warn $fn ("{0} [{1}] has identical Version. Skipping ..." -f $ek.Name, $ek.Id);
			continue;
		}

		$eks.Add($ek); 
	}
	$continuation = $response.GetContinuation();
	if(!$continuation)
	{
		break;
	}
	$response = $svc.Core.Execute($continuation);
}
while($continuation)

```

**Comment by rufer7** [comment]
@seilc1 can we close this issue as soon as the pull request gets merged or is there still something open?

**Comment by rufer7** [comment]
As discussed with @seilc1 we can close this issue.
