### ISSUE TITLE
Create install script

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.PS.Appclusive.Client#4]
Create install script for module installation

**Comment by dfch** [comment]
done

* see [v0.1.7](https://github.com/dfensgmbh/biz.dfch.PS.Appclusive.Client/releases/tag/0.1.7)
* available on [NuGet](https://www.nuget.org/packages/biz.dfch.PS.Appclusive.Client/0.1.7)
* perform `NuGet install biz.dfch.PS.Appclusive.Client -Version 0.1.7` and execute `.\Install.ps1` in downloaded package folder
