### ISSUE TITLE
Add dlls to frameworkAssemblies in .nuspec file

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.PS.Appclusive.Client#6]
Add the following dlls to frameworkAssemblies instead of referencing them in file tags

```
<file src="..\packages\Microsoft.Data.Edm.5.6.4\lib\net40\Microsoft.Data.Edm.dll" target="tools\Microsoft.Data.Edm.dll" />
<file src="..\packages\Microsoft.Data.OData.5.6.4\lib\net40\Microsoft.Data.OData.dll" target="tools\Microsoft.Data.OData.dll" />
<file src="..\packages\Microsoft.Data.Services.Client.5.6.4\lib\net40\Microsoft.Data.Services.Client.dll" target="tools\Microsoft.Data.Services.Client.dll" />
<file src="..\packages\System.Spatial.5.6.4\lib\net40\System.Spatial.dll" target="tools\System.Spatial.dll" />
<file src="..\packages\biz.dfch.CS.Appclusive.Api.1.0.6\lib\biz.dfch.CS.Appclusive.Api.dll" target="tools\biz.dfch.CS.Appclusive.Api.dll" />
```

**Comment by dfch** [comment]
@rufer7 does this work? did you check? from where would these assemblies be loaded?

**Comment by rufer7** [comment]
@dfch I don't know if this works. I only assumed this could be done like this. Fact is it should be possible to build the project on the TeamCity, so the dlls should either be in the repository itself or should be referenced in the nuspec file so that they get downloaded on install. Do you know another possibility how we could solve that?

**Comment by dfch** [comment]
@rufer7 we can define a pre-build step and perform a `nuget install` for dependent packages if they do not already exist

**Comment by rufer7** [comment]
yes we can define a pre build step that installs moudles based on a `package.config` file
