### ISSUE TITLE
Implement Folder Cmdlets

### ISSUE THREAD

**Issue by pbimpisidis** [dfensgmbh/biz.dfch.PS.Appclusive.Client#84]
Create cmdlets for:
- [x] Get-Folder
- [x] New-Folder
- [x] Set-Folder

**Comment by rufer7** [comment]
@pbimpisidis delete is not neesed as we have a general Cndlet for that called `Remove-ApcEntity`

**Comment by rufer7** [comment]
@pbimpisidis furthermore I adjusted the naming of the Cmdlets in the issue description according the convention (Using PowerShell approbed verbs)

**Comment by pbimpisidis** [comment]
@rufer7 thanks!
